# Generated by Django 3.2 on 2022-07-28 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_book_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='likes',
        ),
        migrations.AddField(
            model_name='book',
            name='add_to_whishlist',
            field=models.ManyToManyField(blank=True, related_name='whishlist_add', to=settings.AUTH_USER_MODEL),
        ),
    ]
