# Generated by Django 3.2 on 2022-08-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20220820_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
