# Generated by Django 3.2 on 2022-08-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20220821_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sort',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
