# Generated by Django 3.2 on 2022-08-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_sort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='sort',
            new_name='sort_price',
        ),
    ]
